package orders;

import de.mydomain.drools.model.Order;
import de.mydomain.drools.model.Customer;
import de.mydomain.drools.model.Coupon;
import de.mydomain.drools.model.Discount;
import de.mydomain.drools.model.OrderLine;
import de.mydomain.drools.model.Item;

rule "Classify Customer by order size"
    when
        $o: Order(orderLines.size >= 5, $customer: customer) and
        $c: Customer(this == $customer, category == Customer.Category.NA)
    then
        modify($c){ 
            setCategory(Customer.Category.SILVER)
	    };
end

rule "Create Coupons for Silver Customers"
    when
        $o: Order($customer: customer)
        $c: Customer(this == $customer, category == Category.SILVER )
    then
        insert(new Coupon($c, $o, Coupon.CouponType.POINTS));
end


rule "High Range Order - 10% Discount"
when
    $o: Order($lines : orderLines.size >= 2, discount == null)
    forall(OrderLine(this memberOf $lines, $item : item)
    Item(this == $item, category == Item.Category.HIGH_RANGE))
then
    modify($o){
        setDiscount(new Discount(10.0))
    };
end